security:
  password_hashers:
    App\Entity\User:
            algorithm: plaintext # disable hashing (only do this in tests!)
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "bcrypt"
    
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      form_login:
                username_parameter: user[username]
                password_parameter: user[password]
                login_path: login_page
                check_path: login_page
      logout:
                path: app_logout
                target: home_page

  access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
